### ISSUE TITLE
The browser or operating system may crash if large files are uploaded.

### ISSUE THREAD

**Issue by ghost** [GeeLaw/strcmp.cc#1]
My browser (Edge) as well as the operating system (Windows 10) stopped working as soon as I uploaded two files with the sizes of more than 1MB. It would be better if the program can check the sizes of the files uploaded in advance. If the files uploaded may lead to the crash of the browser or even the operating system, a warning could be displayed.

**Comment by GeeLaw** [comment]
This issue is not reproduced on Windows 10 build 10586 on Surface Pro 3, i7, 128 GB, 8GB.

Step 1: Open Edge.
Step 2: Go to [strcmp.cc](https://strcmp.cc/).
Step 3: Pick file 1 as a file of about 2.35 MB.
Step 4: Pick file 2 as the same file.
Step 5: Tap "compare."

After step 5, the page stops responding due to long-running script. But after about less than 1 minute, the script ends running and the page reads "strcmp **returns** 0."

It might be considered to make the dynamic programming step asynchronous and give time spans for UI responsiveness once a while.

Please specify more details upon the reproduction of this issue.

**Comment by ghost** [comment]
I just had another series of tests. This time I kept waiting until the ends of the halts of the UI, instead of attempting to quit halfway.

First, I uploaded two same files of about 2.76 MB. The browser stopped responding about 80 seconds and then the page shows that 'strcmp **returns** 0', just as what you described above.

Then I uploaded two same files of about 3.88 MB. After waiting about 100 seconds, the screen suddenly turned black (yes, the whole screen). Finding that no responses may occur after another 2 minutes, I shut down my computer by force.

In the third trial, the sizes of the files turned to 7.31 MB. The browser kept responding nothing in the first 7 minutes. Then the screen turned black for several seconds and resumed with the resolution lowered to 800*600. After a while, the computer signed out abruptly.

The device 'sacrificed' for the test is a Surface Book (i7, 512GB, 16GB), running Windows 10 build 10586. No apps are running except the Edge browser used to run the script.

The results may vary under different circumstances, but it's obvious that uploading large files may lead to the crash of the browser or the system. Though only a few users would reach the threshold and trigger the error, the situation of accidentally selecting wrong files cannot be ruled out. Running a size check in advance may tackle this problem.

**Comment by GeeLaw** [comment]
I see the problem here. I conjecture that the device is shut down by the overheat protection module of the system. Thank you for reporting this issue and the issue will be addressed shortly.

**Comment by GeeLaw** [comment]
Ping from Gee :-) Is the issue still present? I think I have fixed it in [this commit](https://github.com/GeeLaw/strcmp.cc/commit/0a7a2a6da80e299c5485eb1cebca209978f31f95).

If the issue is solved, we shall close this issue.

**Comment by ghost** [comment]
Good job! The problem is perfectly solved.

Cheers~
